### ISSUE TITLE
Mobile App ( Send Money Flow )

### ISSUE THREAD

**Issue by Khareem23** [Khareem23/JCI-Global-MobileApp#28]
Bank Identifier ( ABA,BSB) should be an optional field not a mandatory field so remove validation on it
![WhatsApp Image 2022-02-19 at 15 30 12](https://user-images.githubusercontent.com/45461899/154809955-4eed0ca0-9169-455e-8416-790dec868717.jpeg)

**Comment by teesofttech** [comment]
Fixed
