### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by Khareem23** [Khareem23/JCI-Global-MobileApp#29]
Domestic Wire Transfer Page 

![WhatsApp Image 2022-02-19 at 15 38 56](https://user-images.githubusercontent.com/45461899/154810244-4dafa18f-0389-42c5-bf6a-d372f0d83035.jpeg)

Enter Beneficiary Details is wrong . Kindly use "Select Beneficiary Bank" 
This page should only display the banks in the selected country that the Customer is SENDING FROM but instead its displaying all account in our Database.

Also this screen and the next screen seem like repetitions.  
This  screen should display List of banks e.g
Access Bank
GTB
UBA
The customer can choose the bank of their choice

Displaying Details of the Bank is for the Next Screen

**Comment by teesofttech** [comment]
Completed
