### ISSUE TITLE
Mobile App ( Domestic Wire Transfer )

### ISSUE THREAD

**Issue by Khareem23** [Khareem23/JCI-Global-MobileApp#30]
Am not sure about this screen as it doesn't help the user. The details have no titles. Also the header is wrong

Let their be Label for every value you are display e.g 
Bank Name : .........
Bank Account Number : .......
![WhatsApp Image 2022-02-19 at 15 44 41](https://user-images.githubusercontent.com/45461899/154810420-f6b1c82b-0c5c-4f31-98bd-7cd4fc790528.jpeg)

**Comment by teesofttech** [comment]
Completed
