### ISSUE TITLE
Mobile App ( Manual Payment Failed )

### ISSUE THREAD

**Issue by Khareem23** [Khareem23/JCI-Global-MobileApp#31]
There is an error 

We have more fields in our database that should be displayed here like
Bank Identifier and its value should be displayed and more fields you see in the response data etc . 
Display all fields returned by the API here
This shows before and after . 
display all information and fix this error in image 2
![WhatsApp Image 2022-02-19 at 16 21 00](https://user-images.githubusercontent.com/45461899/154810666-ff7d6bd4-58c2-4a56-96b0-669b000d7177.jpeg)
![WhatsApp Image 2022-02-19 at 16 22 44](https://user-images.githubusercontent.com/45461899/154810669-dde4c7c7-3de6-4e44-801f-3cb4fe5b3973.jpeg)

**Comment by teesofttech** [comment]
Fixed
