### ISSUE TITLE
Mobile App ( Registration )

### ISSUE THREAD

**Issue by Khareem23** [Khareem23/JCI-Global-MobileApp#32]
1 :
Phone Number country code should be AUS ( +61 and australia Map ) by default not +234 Nigeria

2: 
On Registration country of Nationality should contain all country's list 

![WhatsApp Image 2022-02-21 at 11 34 53](https://user-images.githubusercontent.com/45461899/154945546-a0c97e3c-07d0-48e6-8cb9-46319468f4f6.jpeg)

**Comment by teesofttech** [comment]
completed
